os: linux

env: IRAFARCH=linux64

language: c

cache:
  ccache: true
  directories:
    - $HOME/.ccache

git:
  depth: 3

before_script:
  - build_tmp=`mktemp -d -t irafbuild.XXXXXXXXX`
  - ./install -v --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir --root `pwd` < /dev/null || true
  - make ${IRAFARCH}
  - make sysgen

script:
  - ./test/run_tests

after_success:
  - curl -s https://codecov.io/bash -o codecov.io.sh
  - patch -p1 < codecov.io.patch
  - bash < codecov.io.sh
